variant: flatcar
version: 1.0.0
storage:
  files:
    - path: /opt/extensions/docker-25.0.3-arm64.raw
      contents:
        source: https://github.com/flatcar/sysext-bakery/releases/download/latest/docker-25.0.3-arm64.raw
    - path: /opt/extensions/docker_compose-2.24.5-arm64.raw
      contents:
        source: https://github.com/flatcar/sysext-bakery/releases/download/latest/docker_compose-2.24.5-arm64.raw
        
    - path: /opt/jitsi/installer/JITSI_VERSION
      mode: 0644
      contents:
        local: JITSI_VERSION

    - path: /opt/jitsi/installer/jitsi-install.sh
      mode: 0755
      contents:
        local: jitsi-install.sh

    - path: /opt/jitsi/installer/config.yaml
      mode: 0644
      contents:
        local: config.yaml

    - path: /opt/jitsi/installer/jitsi.service
      mode: 0644
      contents:
        local: jitsi.service

    - path: /opt/jitsi/installer/branding-docker-compose.yml.patch
      mode: 0644
      contents:
        local: resources/branding-docker-compose.yml.patch

    - path: /opt/jitsi/installer/custom-interface_config.js
      mode: 0644
      contents:
        local: resources/custom-interface_config.js

    - path: /opt/jitsi/installer/flatcar.env
      mode: 0644
      contents:
        local: resources/flatcar.env

    - path: /opt/jitsi/installer/flatcar_banner.png
      mode: 0644
      contents:
        local: resources/flatcar_banner.png

    - path: /opt/jitsi/installer/flatcar_logo-vertical-stacked-black.svg
      mode: 0644
      contents:
        local: resources/flatcar_logo-vertical-stacked-black.svg

    - path: /opt/jitsi/installer/flatcar_logo-vertical-stacked.svg
      mode: 0644
      contents:
        local: resources/flatcar_logo-vertical-stacked.svg

  links:
    - path: /etc/extensions/docker-flatcar.raw
      target: /dev/null
      overwrite: true
    - path: /etc/extensions/containerd-flatcar.raw
      target: /dev/null
      overwrite: true
    - path: /etc/extensions/docker.raw
      target: /opt/extensions/docker-25.0.3-arm64.raw
      overwrite: true
    - path: /etc/extensions/docker_compose.raw
      target: /opt/extensions/docker_compose-2.24.5-arm64.raw
      overwrite: true
passwd:
  #groups:
    #- name: jitsi 
  users:
    - name: jitsi
      #system: true 
      #create:
      groups: [ sudo, docker ]
