variant: flatcar
version: 1.0.0
storage:
  files:
    - path: /opt/extensions/docker-25.0.3-arm64.raw
      contents:
        source: https://github.com/flatcar/sysext-bakery/releases/download/latest/docker-25.0.3-arm64.raw
    - path: /opt/extensions/docker_compose-2.24.5-arm64.raw
      contents:
        source: https://github.com/flatcar/sysext-bakery/releases/download/latest/docker_compose-2.24.5-arm64.raw



    - path: /opt/jitsi/installer/flatcar-jitsi.sh
      mode: 0755
      contents:
        local: flatcar-jitsi.sh


  links:
    - path: /etc/extensions/docker-flatcar.raw
      target: /dev/null
      overwrite: true
    - path: /etc/extensions/containerd-flatcar.raw
      target: /dev/null
      overwrite: true
    - path: /etc/extensions/docker.raw
      target: /opt/extensions/docker-25.0.3-arm64.raw
      overwrite: true
    - path: /etc/extensions/docker_compose.raw
      target: /opt/extensions/docker_compose-2.24.5-arm64.raw
      overwrite: true
passwd:
  #groups:
    #- name: jitsi 
  users:
    - name: jitsi
      #system: true 
      #create:
      groups: [ sudo, docker ]
